### ISSUE TITLE
Backend still English

### ISSUE THREAD

**Issue by nickweisser** [openstream/Magento2_German_LocalePack_de_CH#2]
Although German translations are being displayed in the frontend in most places, the backend is still completely English. Any ideas what I might be missing here?

**Comment by splendidinternet** [comment]
@nickw108 
in our shop it's german:
![image](https://cloud.githubusercontent.com/assets/673488/13300638/743b45ca-db41-11e5-9412-b9e0050b9f5c.png)

**Comment by nickweisser** [comment]
Thanks for the screenshot, will make another test with de_DE and see if it's working there.

**Comment by niclashoyer** [comment]
As far as I can tell the "default" language for admin users is english, so even after installing the language pack you'll have to change the language for the admin users.

**Comment by nickweisser** [comment]
Thank you so much for the pointer, I didn't realize that the language has to be changed in the admin user, too. That's new in Magento 2 😅
