### ISSUE TITLE
%1,1% - Zeile 87

### ISSUE THREAD

**Issue by bh-ref** [openstream/Magento2_German_LocalePack_de_CH#3]
Hallo, vielen Dank für die Übersetzung!

In Zeile 87 übersetzt ihr "%1" mit "1%", das führt im Backend von Magento 2.1 beim Bearbeiten der Produkte zu einer falschen Übersetzung, siehe https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/issues/27

**Comment by nickweisser** [comment]
Wurde im Upstream in c4655011e74783252a4bb9b193929d0c934bbc85 gefixt.
