### ISSUE TITLE
Component Manager states error "Couldn't get available versions for package openstream/mage2-locale-de-ch"

### ISSUE THREAD

**Issue by Anis108** [openstream/Magento2_German_LocalePack_de_CH#4]
Hello 
After installing the package with the composer I receive on the Component Manager

Couldn't get available versions for package openstream/mage2-locale-de-ch

This blocks the function to install apps from the magento market place.
Please suggest how to proceed or correct that?

**Comment by nickweisser** [comment]
Didn't have time to test this yet, might take some time. Sorry.

**Comment by superhigi** [comment]
Still no news on this?

**Comment by Anis108** [comment]
Here as a hint to a fix that should be available in some time:

https://github.com/magento/magento2/issues/6718
https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/issues/42
